- throat
- punch
- fuck
- shit
- squat
- grind
- blood
- skull
- axle
- gulch
- dirt
- slave
- shred
- murder
- wrench
- hammer
- saw
- nail
- finger
- bone
- splinter
- steel
- iron
- metal
- smoke
- grime
- throb
- slice
- mud
- razor
- spike
- chain
- bolt
- kill
- killer
- murder
- maim
- grub
- fiend
- screech
- gut
- rust
- slap
- dead
- scar
